/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRecycleBinRouteImport } from './routes/_authenticated/recycle-bin'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedWorkshopsIndexRouteImport } from './routes/_authenticated/workshops.index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients.index'
import { Route as AuthenticatedWorkshopsIdRouteImport } from './routes/_authenticated/workshops.$id'
import { Route as AuthenticatedDashboardMetricRouteImport } from './routes/_authenticated/dashboard.$metric'
import { Route as AuthenticatedClientsIdRouteImport } from './routes/_authenticated/clients.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecycleBinRoute = AuthenticatedRecycleBinRouteImport.update({
  id: '/recycle-bin',
  path: '/recycle-bin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkshopsIndexRoute =
  AuthenticatedWorkshopsIndexRouteImport.update({
    id: '/workshops/',
    path: '/workshops/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkshopsIdRoute =
  AuthenticatedWorkshopsIdRouteImport.update({
    id: '/workshops/$id',
    path: '/workshops/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardMetricRoute =
  AuthenticatedDashboardMetricRouteImport.update({
    id: '/$metric',
    path: '/$metric',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedClientsIdRoute = AuthenticatedClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/expenses': typeof AuthenticatedExpensesRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/recycle-bin': typeof AuthenticatedRecycleBinRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/dashboard/$metric': typeof AuthenticatedDashboardMetricRoute
  '/workshops/$id': typeof AuthenticatedWorkshopsIdRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/workshops/': typeof AuthenticatedWorkshopsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/recycle-bin': typeof AuthenticatedRecycleBinRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/dashboard/$metric': typeof AuthenticatedDashboardMetricRoute
  '/workshops/$id': typeof AuthenticatedWorkshopsIdRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/workshops': typeof AuthenticatedWorkshopsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/recycle-bin': typeof AuthenticatedRecycleBinRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/clients/$id': typeof AuthenticatedClientsIdRoute
  '/_authenticated/dashboard/$metric': typeof AuthenticatedDashboardMetricRoute
  '/_authenticated/workshops/$id': typeof AuthenticatedWorkshopsIdRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/workshops/': typeof AuthenticatedWorkshopsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/activity'
    | '/calendar'
    | '/dashboard'
    | '/expenses'
    | '/payments'
    | '/recycle-bin'
    | '/reports'
    | '/settings'
    | '/clients/$id'
    | '/dashboard/$metric'
    | '/workshops/$id'
    | '/clients/'
    | '/dashboard/'
    | '/workshops/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/activity'
    | '/calendar'
    | '/expenses'
    | '/payments'
    | '/recycle-bin'
    | '/reports'
    | '/settings'
    | '/clients/$id'
    | '/dashboard/$metric'
    | '/workshops/$id'
    | '/clients'
    | '/dashboard'
    | '/workshops'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/activity'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/expenses'
    | '/_authenticated/payments'
    | '/_authenticated/recycle-bin'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/clients/$id'
    | '/_authenticated/dashboard/$metric'
    | '/_authenticated/workshops/$id'
    | '/_authenticated/clients/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/workshops/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recycle-bin': {
      id: '/_authenticated/recycle-bin'
      path: '/recycle-bin'
      fullPath: '/recycle-bin'
      preLoaderRoute: typeof AuthenticatedRecycleBinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workshops/': {
      id: '/_authenticated/workshops/'
      path: '/workshops'
      fullPath: '/workshops/'
      preLoaderRoute: typeof AuthenticatedWorkshopsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workshops/$id': {
      id: '/_authenticated/workshops/$id'
      path: '/workshops/$id'
      fullPath: '/workshops/$id'
      preLoaderRoute: typeof AuthenticatedWorkshopsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/$metric': {
      id: '/_authenticated/dashboard/$metric'
      path: '/$metric'
      fullPath: '/dashboard/$metric'
      preLoaderRoute: typeof AuthenticatedDashboardMetricRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/clients/$id': {
      id: '/_authenticated/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthenticatedClientsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardMetricRoute: typeof AuthenticatedDashboardMetricRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardMetricRoute: AuthenticatedDashboardMetricRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedRecycleBinRoute: typeof AuthenticatedRecycleBinRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedClientsIdRoute: typeof AuthenticatedClientsIdRoute
  AuthenticatedWorkshopsIdRoute: typeof AuthenticatedWorkshopsIdRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedWorkshopsIndexRoute: typeof AuthenticatedWorkshopsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedRecycleBinRoute: AuthenticatedRecycleBinRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedClientsIdRoute: AuthenticatedClientsIdRoute,
  AuthenticatedWorkshopsIdRoute: AuthenticatedWorkshopsIdRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedWorkshopsIndexRoute: AuthenticatedWorkshopsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
